### ISSUE TITLE
jQuery missing

### ISSUE THREAD

**Issue by melicerte** [Orange-OpenSource/just-drop-it#24]
Hi,

I tried to launch the docker example as described 
`docker build -t just-drop-it`
and then 
`docker run --name just-drop-it -p 8080:8080 -d just-drop-it`

But I then got the following error in the browser console :
`Failed to load resource: the server responded with a status of 404 (Not Found)`

Code is in HTML :
`<script src="/jquery.js"></script>`

**Comment by melicerte** [comment]
It works if I write 
`app.use(express.static(path.join(__dirname, path.join('node_modules', 'jquery', 'dist'))));`
instead of
`app.use(express.static(path.join(__dirname, path.join('node_modules', 'jquery', 'dist','cdn'))));`

**Comment by antechrestos** [comment]
Thanks for your feedback. Please provide a pull request or wait for me to take a look at it.

**Comment by antechrestos** [comment]
@melicerte thank you for spotting the issue, I made a match and a release
