### ISSUE TITLE
The promised online demo

### ISSUE THREAD

**Issue by vinyll** [Orange-OpenSource/just-drop-it#44]
https://github.com/Orange-OpenSource/just-drop-it#how-to-use-it

_or wait for our online demo. A few days, we promise :smile:_

It's been many few days ;)

**Comment by ShalokShalom** [comment]
I guess Oracle Free Tier could be an option. 
https://www.oracle.com/cloud/free/

In any case: The README still promotes an online demo, so I guess it can be removed, if we dont find a way to host this.

**Comment by arnaudruffin** [comment]
Thanks for the tip @ShalokShalom. We'll be happy to accept your contribution if you managed to host it.

**Comment by vinyll** [comment]
These guys seems to do hosting: https://cloud.orange-business.com/en/

They seem to be your company. Can’t they support open source providing a small cloud cluster?

**Comment by bbailleux** [comment]
The reference to a future online demo has been removed.

So sorry about that (thanks @ShalokShalom for the suggestion)
